//
//  FashionProductInteractor.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class FashionProductInteractor/*: FashionProductViewControllerDataSource */ {
//    //Data passing
//    var dataPassing: AnyObject?
    //swiftlint:disable all
    var output: FashionProductInteractorOutputProtocol!
    var worker: FashionProductWorker!
    //swiftlint:enable all
}

extension FashionProductInteractor: FashionProductViewControllerOutputProtocol {

}

