//
//  FashionProductConfigurator.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

import UIKit

class FashionProductConfigurator {
    
    // MARK: Configuration
    class func viewcontroller() -> FashionProductViewController {
        let viewController = FashionProductViewController(nibName: "FashionProductViewController", bundle: nil)
        
        let presenter = FashionProductPresenter()
        presenter.output = viewController
        
        let interactor = FashionProductInteractor()
        interactor.output = presenter
        
        let router = FashionProductRouter()
        router.viewController = viewController

//        //Data passing
//        router.dataSource = interactor
        
        viewController.output = interactor
        viewController.router = router
        
        return viewController
    }
}

//// MARK: Data passing
//protocol FashionProductViewControllerDataSource: class {
//    //Must be a struct model
//    var dataPassing: AnyObject? {
//        get set
//    }
//}

// MARK: View Interface
protocol FashionProductViewControllerOutputProtocol {

}

// MARK: Interactor Interface
protocol FashionProductInteractorOutputProtocol {

}

// MARK: Presenter Interface
protocol FashionProductPresenterOutputProtocol: class {
    
}

// MARK: Router
protocol FashionProductRouterProtocol {

}
