//
//  PageTabLoginAndRegisterAccountViewController.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

import UIKit
import XLPagerTabStrip

// MARK: View
class PageTabLoginAndRegisterAccountViewController: ButtonBarPagerTabStripViewController {
    //swiftlint:disable all
    var output: PageTabLoginAndRegisterAccountViewControllerOutputProtocol!
    var router: PageTabLoginAndRegisterAccountRouter!
    //swiftlint:enable all
    var viewModel: PageTabLoginAndRegisterAccountModel.ViewModel?
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        fetchDataOnLoad()
        
//        self.navigationController?.setNavigationBarHidden(true, animated: true)
    }
    
    // MARK: Fetch PageTabLoginAndRegisterAccount
    private func fetchDataOnLoad() {
        settings.style.buttonBarBackgroundColor = .white
        settings.style.buttonBarItemBackgroundColor = .white
        settings.style.selectedBarBackgroundColor = .orange
        settings.style.buttonBarItemFont = .boldSystemFont(ofSize: 14)
        settings.style.selectedBarHeight = 2.0
        settings.style.buttonBarMinimumLineSpacing = 0
        settings.style.buttonBarItemTitleColor = .black
        settings.style.buttonBarItemsShouldFillAvailableWidth = true
        settings.style.buttonBarLeftContentInset = 0
        settings.style.buttonBarRightContentInset = 0
        
    }
    
    override func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController] {
        let child1 = LoginViewController(itemInfo: "Đăng Nhập")
        let child2 = RegisterAccountViewController(itemInfo: "Đăng Ký")
        return [child1, child2]
    }
   
}

// MARK: Connect View, Interactor, and Presenter
extension PageTabLoginAndRegisterAccountViewController: PageTabLoginAndRegisterAccountPresenterOutputProtocol {
    
}
