//
//  LoginWorker.swift
//  VIPTemplate
//
//  Created Nguyen Chi Hieu on 6/15/18.
//  Copyright © 2018 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class LoginWorker {
    // MARK: Business Logic
    
    func doSomeWork() {
        // NOTE: Do the work
    }
}
