//
//  PageTabHomeInteractor.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class PageTabHomeInteractor/*: PageTabHomeViewControllerDataSource */ {
//    //Data passing
//    var dataPassing: AnyObject?
    //swiftlint:disable all
    var output: PageTabHomeInteractorOutputProtocol!
    var worker: PageTabHomeWorker!
    //swiftlint:enable all
}

extension PageTabHomeInteractor: PageTabHomeViewControllerOutputProtocol {

}

