//
//  PageTabHomeConfigurator.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

import UIKit

class PageTabHomeConfigurator {
    
    // MARK: Configuration
    class func viewcontroller() -> PageTabHomeViewController {
//        let viewController = PageTabHomeViewController(nibName: "PageTabHomeViewController", bundle: nil)
        let storyboard = UIStoryboard(name: "PageTabHome", bundle: nil)
        guard let viewController = storyboard.instantiateInitialViewController() as? PageTabHomeViewController else {
            fatalError("fail to init TrackingViewController from Profile storyboard")
        }
        
        let presenter = PageTabHomePresenter()
        presenter.output = viewController
        
        let interactor = PageTabHomeInteractor()
        interactor.output = presenter
        
        let router = PageTabHomeRouter()
        router.viewController = viewController

//        //Data passing
//        router.dataSource = interactor
        
        viewController.output = interactor
        viewController.router = router
        
        return viewController
    }
}

//// MARK: Data passing
//protocol PageTabHomeViewControllerDataSource: class {
//    //Must be a struct model
//    var dataPassing: AnyObject? {
//        get set
//    }
//}

// MARK: View Interface
protocol PageTabHomeViewControllerOutputProtocol {

}

// MARK: Interactor Interface
protocol PageTabHomeInteractorOutputProtocol {

}

// MARK: Presenter Interface
protocol PageTabHomePresenterOutputProtocol: class {
    
}

// MARK: Router
protocol PageTabHomeRouterProtocol {

}
