//
//  PageTabHomePresenter.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class PageTabHomePresenter {
    //swiftlint:disable all
    weak var output: PageTabHomePresenterOutputProtocol!
    //swiftlint:enable all
}

extension PageTabHomePresenter: PageTabHomeInteractorOutputProtocol {
  
}
