//
//  MakeUpProductPresenter.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class MakeUpProductPresenter {
    //swiftlint:disable all
    weak var output: MakeUpProductPresenterOutputProtocol!
    //swiftlint:enable all
}

extension MakeUpProductPresenter: MakeUpProductInteractorOutputProtocol {
  
}
