//
//  MakeUpProductInteractor.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class MakeUpProductInteractor/*: MakeUpProductViewControllerDataSource */ {
//    //Data passing
//    var dataPassing: AnyObject?
    //swiftlint:disable all
    var output: MakeUpProductInteractorOutputProtocol!
    var worker: MakeUpProductWorker!
    //swiftlint:enable all
}

extension MakeUpProductInteractor: MakeUpProductViewControllerOutputProtocol {

}

