//
//  PageTabLoginAndRegisterAccountInteractor.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class PageTabLoginAndRegisterAccountInteractor/*: PageTabLoginAndRegisterAccountViewControllerDataSource */ {
//    //Data passing
//    var dataPassing: AnyObject?
    //swiftlint:disable all
    var output: PageTabLoginAndRegisterAccountInteractorOutputProtocol!
    var worker: PageTabLoginAndRegisterAccountWorker!
    //swiftlint:enable all
}

extension PageTabLoginAndRegisterAccountInteractor: PageTabLoginAndRegisterAccountViewControllerOutputProtocol {

}

