//
//  PageTabLoginAndRegisterAccountPresenter.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class PageTabLoginAndRegisterAccountPresenter {
    //swiftlint:disable all
    weak var output: PageTabLoginAndRegisterAccountPresenterOutputProtocol!
    //swiftlint:enable all
}

extension PageTabLoginAndRegisterAccountPresenter: PageTabLoginAndRegisterAccountInteractorOutputProtocol {
  
}
