//
//  PageTabLoginAndRegisterAccountConfigurator.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

import UIKit

class PageTabLoginAndRegisterAccountConfigurator {
    
    // MARK: Configuration
    class func viewcontroller() -> PageTabLoginAndRegisterAccountViewController {
//        let viewController = PageTabLoginAndRegisterAccountViewController(nibName: "PageTabLoginAndRegisterAccountViewController", bundle: nil)
        let storyboard = UIStoryboard(name: "PageTabLoginAndRegisterAccount", bundle: nil)
        guard let viewController = storyboard.instantiateInitialViewController() as? PageTabLoginAndRegisterAccountViewController else {
            fatalError("fail to init TrackingViewController from Profile storyboard")
        }
        
        let presenter = PageTabLoginAndRegisterAccountPresenter()
        presenter.output = viewController
        
        let interactor = PageTabLoginAndRegisterAccountInteractor()
        interactor.output = presenter
        
        let router = PageTabLoginAndRegisterAccountRouter()
        router.viewController = viewController

//        //Data passing
//        router.dataSource = interactor
        
        viewController.output = interactor
        viewController.router = router
        
        return viewController
    }
}

//// MARK: Data passing
//protocol PageTabLoginAndRegisterAccountViewControllerDataSource: class {
//    //Must be a struct model
//    var dataPassing: AnyObject? {
//        get set
//    }
//}

// MARK: View Interface
protocol PageTabLoginAndRegisterAccountViewControllerOutputProtocol {

}

// MARK: Interactor Interface
protocol PageTabLoginAndRegisterAccountInteractorOutputProtocol {

}

// MARK: Presenter Interface
protocol PageTabLoginAndRegisterAccountPresenterOutputProtocol: class {
    
}

// MARK: Router
protocol PageTabLoginAndRegisterAccountRouterProtocol {

}
