//
//  ElectronicProductConfigurator.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

import UIKit

class ElectronicProductConfigurator {
    
    // MARK: Configuration
    class func viewcontroller() -> ElectronicProductViewController {
//        let viewController = ElectronicProductViewController(nibName: "ElectronicProductViewController", bundle: nil)

        let viewController = ElectronicProductViewController(itemInfo: "FOLLOWING")

        let presenter = ElectronicProductPresenter()
        presenter.output = viewController
        
        let interactor = ElectronicProductInteractor()
        interactor.output = presenter
        
        let router = ElectronicProductRouter()
        router.viewController = viewController

//        //Data passing
//        router.dataSource = interactor
        
        viewController.output = interactor
        viewController.router = router
        
        return viewController
    }
}

//// MARK: Data passing
//protocol ElectronicProductViewControllerDataSource: class {
//    //Must be a struct model
//    var dataPassing: AnyObject? {
//        get set
//    }
//}

// MARK: View Interface
protocol ElectronicProductViewControllerOutputProtocol {

}

// MARK: Interactor Interface
protocol ElectronicProductInteractorOutputProtocol {

}

// MARK: Presenter Interface
protocol ElectronicProductPresenterOutputProtocol: class {
    
}

// MARK: Router
protocol ElectronicProductRouterProtocol {

}
