//
//  ElectronicProductPresenter.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class ElectronicProductPresenter {
    //swiftlint:disable all
    weak var output: ElectronicProductPresenterOutputProtocol!
    //swiftlint:enable all
}

extension ElectronicProductPresenter: ElectronicProductInteractorOutputProtocol {
  
}
