//
//  ElectronicProductInteractor.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class ElectronicProductInteractor/*: ElectronicProductViewControllerDataSource */ {
//    //Data passing
//    var dataPassing: AnyObject?
    //swiftlint:disable all
    var output: ElectronicProductInteractorOutputProtocol!
    var worker: ElectronicProductWorker!
    //swiftlint:enable all
}

extension ElectronicProductInteractor: ElectronicProductViewControllerOutputProtocol {

}

