//
//  LoginPresenter.swift
//  VIPTemplate
//
//  Created Nguyen Chi Hieu on 6/15/18.
//  Copyright © 2018 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class LoginPresenter {
    //swiftlint:disable all
    weak var output: LoginPresenterProtocol!
    //swiftlint:enable all
}

extension LoginPresenter: LoginInteractorProtocol {
  
}
