//
//  LoginInteractor.swift
//  VIPTemplate
//
//  Created Nguyen Chi Hieu on 6/15/18.
//  Copyright © 2018 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class LoginInteractor {
    //swiftlint:disable all
    var output: LoginInteractorProtocol!
    var worker: LoginWorker!
    //swiftlint:enable all
}

extension LoginInteractor: LoginViewControllerProtocol {

}

