//
//  RegisterAccountPresenter.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/5/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class RegisterAccountPresenter {
    //swiftlint:disable all
    weak var output: RegisterAccountPresenterOutputProtocol!
    //swiftlint:enable all
}

extension RegisterAccountPresenter: RegisterAccountInteractorOutputProtocol {
  
}
