//
//  RegisterAccountConfigurator.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/5/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

import UIKit

class RegisterAccountConfigurator {
    
    // MARK: Configuration
    class func viewcontroller() -> RegisterAccountViewController {
//        let viewController = RegisterAccountViewController(nibName: "RegisterAccountViewController", bundle: nil)
        
        let viewController = RegisterAccountViewController(itemInfo: "FOLLOWING")
        
        let presenter = RegisterAccountPresenter()
        presenter.output = viewController
        
        let interactor = RegisterAccountInteractor()
        interactor.output = presenter
        
        let router = RegisterAccountRouter()
        router.viewController = viewController

//        //Data passing
//        router.dataSource = interactor
        
        viewController.output = interactor
        viewController.router = router
        
        return viewController
    }
}

//// MARK: Data passing
//protocol RegisterAccountViewControllerDataSource: class {
//    //Must be a struct model
//    var dataPassing: AnyObject? {
//        get set
//    }
//}

// MARK: View Interface
protocol RegisterAccountViewControllerOutputProtocol {

}

// MARK: Interactor Interface
protocol RegisterAccountInteractorOutputProtocol {

}

// MARK: Presenter Interface
protocol RegisterAccountPresenterOutputProtocol: class {
    
}

// MARK: Router
protocol RegisterAccountRouterProtocol {

}
