//
//  RegisterAccountInteractor.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/5/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class RegisterAccountInteractor/*: RegisterAccountViewControllerDataSource */ {
//    //Data passing
//    var dataPassing: AnyObject?
    //swiftlint:disable all
    var output: RegisterAccountInteractorOutputProtocol!
    var worker: RegisterAccountWorker!
    //swiftlint:enable all
}

extension RegisterAccountInteractor: RegisterAccountViewControllerOutputProtocol {

}

