//
//  TrademarkProductInteractor.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class TrademarkProductInteractor/*: TrademarkProductViewControllerDataSource */ {
//    //Data passing
//    var dataPassing: AnyObject?
    //swiftlint:disable all
    var output: TrademarkProductInteractorOutputProtocol!
    var worker: TrademarkProductWorker!
    //swiftlint:enable all
}

extension TrademarkProductInteractor: TrademarkProductViewControllerOutputProtocol {

}

