//
//  MunAndBabyProductViewController.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

import UIKit
import XLPagerTabStrip

// MARK: View
class MunAndBabyProductViewController: UIViewController, IndicatorInfoProvider {
    
    //swiftlint:disable all
    var output: MunAndBabyProductViewControllerOutputProtocol!
    var router: MunAndBabyProductRouter!
    //swiftlint:enable all
    var viewModel: MunAndBabyProductModel.ViewModel?
    var itemInfo: IndicatorInfo = "View"

    
    init(itemInfo: IndicatorInfo) {
        self.itemInfo = itemInfo
        super.init(nibName: "MunAndBabyProductViewController", bundle: nil)
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        fetchDataOnLoad()
    }
    
    // MARK: Fetch MunAndBabyProduct
    private func fetchDataOnLoad() {
        // NOTE: Ask the Interactor to do some work
        
    }
    
    func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
        return itemInfo
    }
   
}

// MARK: Connect View, Interactor, and Presenter
extension MunAndBabyProductViewController: MunAndBabyProductPresenterOutputProtocol {
    
}
