# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

private_lane :build_application do |options|
  # This part is done only when the app is not for the "production" environment
  if not options[:release]
    # Modulate the color of the icons
    color_icon(
      modulation: "#{options[:modulation]}"
    )
    # Add the build number to the icon
    build_number_icon
  end

  # Update the app identifier
  update_app_identifier(
    xcodeproj: "#{options[:project_name]}.xcodeproj",
    plist_path: "Sources/Info.plist",
    app_identifier: options[:app_identifier]
  )

  # Install the certificate
  # import_certificate(
  #   certificate_path: options[:certificate_path],
  #   certificate_password: options[:certificate_password],
  #   keychain_name: "login.keychain"
  # )

  # # Install the provisioning profile
  # update_project_provisioning(
  #   xcodeproj: "#{options[:project_name]}.xcodeproj",
  #   profile: options[:profile]
  # )

  # Version bump
  increment_build_number(
    build_number: options[:build_number]
  )

  cocoapods(
  	clean: true
  )

  clear_derived_data

  # Build the app
  gym(
    workspace: "#{options[:project_name]}.xcworkspace",
    scheme: "#{options[:scheme]}",
    configuration: options[:configuration],
    clean: true,
    include_bitcode: false,
    output_directory:"./fastlane",
    export_method: options[:export_method]
  )

end

private_lane :beta do
  # ...
  crashlytics(api_token: "a67aca74f5ba7a6a656613c1a10eff7041a5dcc1",
              build_secret: "16086b24b6ed5337b203609c55f75889d93384f31f625563cd3888399f9d60a3")
end

# Build and publish the Release version to the AppStore
lane :release_beta do
  # Build
  build_application(
    # Not a production release, so add build number and do the color modulation of the icons
    release:true,
    # Set the app id
    app_identifier:"com.savvycom.viptemplate",
    # Set the path to the certificate to use in building
    # certificate_path:"./fastlane/certs/vip_template.p12",
    # Set the password of the p12 certificate file
    # certificate_password:"",
    # Set the path to the provisioning profile to use (change this!)
    # profile:"./fastlane/certs/vip_template_adhoc.mobileprovision",
    # Set the name to the provisioning profile to use (change this!)
    # profile_name:"vip_template_adhoc",
    # What configuration to use, usefull for keeping different API keys etc between environments
    configuration:"Debug",
    # Use this codesigning identity (this is the name of the certificate in your keychain)
    codesigning_identity:"iPhone Distribution: Savvycom JSC",
    # Export an enterprise app
    export_method:"development",
    # the projectname, this is the name of the .xcodeproj file and the folder containing your code in the project
    project_name:"VIPTemplate",
    # the scheme to build
    scheme:"VIPTemplate",
    # the build number to use, we use the build number from Jenkins
    build_number: ENV["BUILD_NUMBER"]
  )
  # Push to the beta
  beta

end


# Publish to the AppStore
private_lane :publish_appstore do |options|
  deliver(force: true)
end

# Build and publish the Release version to the AppStore
lane :release_appstore do
  # Build
  build_application(
    # Not a production release, so add build number and do the color modulation of the icons
    release:true,
    # Set the app id
    app_identifier:"com.savvycom.viptemplate",
    # Set the path to the certificate to use in building
    # certificate_path:"./fastlane/certs/vip_template.p12",
    # Set the password of the p12 certificate file
    # certificate_password:"",
    # Set the path to the provisioning profile to use (change this!)
    # profile:"./fastlane/certs/vip_template_adhoc.mobileprovision",
    # Set the name to the provisioning profile to use (change this!)
    # profile_name:"vip_template_adhoc",
    # What configuration to use, usefull for keeping different API keys etc between environments
    configuration:"Production",
    # Use this codesigning identity (this is the name of the certificate in your keychain)
    codesigning_identity:"iPhone Distribution: Savvycom JSC",
    # Export an enterprise app
    export_method:"app-store",
    # the projectname, this is the name of the .xcodeproj file and the folder containing your code in the project
    project_name:"VIPTemplate",
    # the scheme to build
    scheme:"VIPTemplateAppStore",
    # the build number to use, we use the build number from Jenkins
    build_number: ENV["BUILD_NUMBER"]
  )
  # Push to the appstore
  publish_appstore

end


end
