//
//  PageTabHomeWorker.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class PageTabHomeWorker {
    // MARK: Business Logic
    
    func doSomeWork() {
        // NOTE: Do the work
    }
}
