//
//  SportAndTourProductPresenter.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class SportAndTourProductPresenter {
    //swiftlint:disable all
    weak var output: SportAndTourProductPresenterOutputProtocol!
    //swiftlint:enable all
}

extension SportAndTourProductPresenter: SportAndTourProductInteractorOutputProtocol {
  
}
