//
//  SportAndTourProductConfigurator.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

import UIKit

class SportAndTourProductConfigurator {
    
    // MARK: Configuration
    class func viewcontroller() -> SportAndTourProductViewController {
//        let viewController = SportAndTourProductViewController(nibName: "SportAndTourProductViewController", bundle: nil)
        let viewController = SportAndTourProductViewController(itemInfo: "FOLLOWING")

        let presenter = SportAndTourProductPresenter()
        presenter.output = viewController
        
        let interactor = SportAndTourProductInteractor()
        interactor.output = presenter
        
        let router = SportAndTourProductRouter()
        router.viewController = viewController

//        //Data passing
//        router.dataSource = interactor
        
        viewController.output = interactor
        viewController.router = router
        
        return viewController
    }
}

//// MARK: Data passing
//protocol SportAndTourProductViewControllerDataSource: class {
//    //Must be a struct model
//    var dataPassing: AnyObject? {
//        get set
//    }
//}

// MARK: View Interface
protocol SportAndTourProductViewControllerOutputProtocol {

}

// MARK: Interactor Interface
protocol SportAndTourProductInteractorOutputProtocol {

}

// MARK: Presenter Interface
protocol SportAndTourProductPresenterOutputProtocol: class {
    
}

// MARK: Router
protocol SportAndTourProductRouterProtocol {

}
