//
//  FeaturedProductInteractor.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class FeaturedProductInteractor/*: FeaturedProductViewControllerDataSource */ {
//    //Data passing
//    var dataPassing: AnyObject?
    //swiftlint:disable all
    var output: FeaturedProductInteractorOutputProtocol!
    var worker: FeaturedProductWorker!
    //swiftlint:enable all
}

extension FeaturedProductInteractor: FeaturedProductViewControllerOutputProtocol {

}

