//
//  FeaturedProductConfigurator.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

import UIKit

class FeaturedProductConfigurator {
    
    // MARK: Configuration
    class func viewcontroller() -> FeaturedProductViewController {
//        let viewController = FeaturedProductViewController(nibName: "FeaturedProductViewController", bundle: nil)
        let viewController = FeaturedProductViewController(itemInfo: "FOLLOWING")
        
        let presenter = FeaturedProductPresenter()
        presenter.output = viewController
        
        let interactor = FeaturedProductInteractor()
        interactor.output = presenter
        
        let router = FeaturedProductRouter()
        router.viewController = viewController

//        //Data passing
//        router.dataSource = interactor
        
        viewController.output = interactor
        viewController.router = router
        
        return viewController
    }
}

//// MARK: Data passing
//protocol FeaturedProductViewControllerDataSource: class {
//    //Must be a struct model
//    var dataPassing: AnyObject? {
//        get set
//    }
//}

// MARK: View Interface
protocol FeaturedProductViewControllerOutputProtocol {

}

// MARK: Interactor Interface
protocol FeaturedProductInteractorOutputProtocol {

}

// MARK: Presenter Interface
protocol FeaturedProductPresenterOutputProtocol: class {
    
}

// MARK: Router
protocol FeaturedProductRouterProtocol {

}
