//
//  FeaturedProductPresenter.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class FeaturedProductPresenter {
    //swiftlint:disable all
    weak var output: FeaturedProductPresenterOutputProtocol!
    //swiftlint:enable all
}

extension FeaturedProductPresenter: FeaturedProductInteractorOutputProtocol {
  
}
