//
//  SportAndTourProductViewController.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

import UIKit
import XLPagerTabStrip

// MARK: View
class SportAndTourProductViewController: UIViewController, IndicatorInfoProvider {
    //swiftlint:disable all
    var output: SportAndTourProductViewControllerOutputProtocol!
    var router: SportAndTourProductRouter!
    //swiftlint:enable all
    var viewModel: SportAndTourProductModel.ViewModel?
    var itemInfo: IndicatorInfo = "View"

    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        fetchDataOnLoad()
    }
    
    init(itemInfo: IndicatorInfo) {
        self.itemInfo = itemInfo
        super.init(nibName: "SportAndTourProductViewController", bundle: nil)
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    // MARK: Fetch SportAndTourProduct
    private func fetchDataOnLoad() {
        // NOTE: Ask the Interactor to do some work
        
    }
    
    func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
        return itemInfo
    }
   
}

// MARK: Connect View, Interactor, and Presenter
extension SportAndTourProductViewController: SportAndTourProductPresenterOutputProtocol {
    
}
