//
//  RegisterAccountViewModel.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/5/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

struct RegisterAccountModel {
    struct Request {
        
    }
    
    struct Response {
        
    }
    
    struct ViewModel {
        
    }
}
