//
//  MunAndBabyProductConfigurator.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

import UIKit

class MunAndBabyProductConfigurator {
    
    // MARK: Configuration
    class func viewcontroller() -> MunAndBabyProductViewController {
//        let viewController = MunAndBabyProductViewController(nibName: "MunAndBabyProductViewController", bundle: nil)
        let viewController = MunAndBabyProductViewController(itemInfo: "FOLLOWING")

        let presenter = MunAndBabyProductPresenter()
        presenter.output = viewController
        
        let interactor = MunAndBabyProductInteractor()
        interactor.output = presenter
        
        let router = MunAndBabyProductRouter()
        router.viewController = viewController

//        //Data passing
//        router.dataSource = interactor
        
        viewController.output = interactor
        viewController.router = router
        
        return viewController
    }
}

//// MARK: Data passing
//protocol MunAndBabyProductViewControllerDataSource: class {
//    //Must be a struct model
//    var dataPassing: AnyObject? {
//        get set
//    }
//}

// MARK: View Interface
protocol MunAndBabyProductViewControllerOutputProtocol {

}

// MARK: Interactor Interface
protocol MunAndBabyProductInteractorOutputProtocol {

}

// MARK: Presenter Interface
protocol MunAndBabyProductPresenterOutputProtocol: class {
    
}

// MARK: Router
protocol MunAndBabyProductRouterProtocol {

}
