//
//  MunAndBabyProductInteractor.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class MunAndBabyProductInteractor/*: MunAndBabyProductViewControllerDataSource */ {
//    //Data passing
//    var dataPassing: AnyObject?
    //swiftlint:disable all
    var output: MunAndBabyProductInteractorOutputProtocol!
    var worker: MunAndBabyProductWorker!
    //swiftlint:enable all
}

extension MunAndBabyProductInteractor: MunAndBabyProductViewControllerOutputProtocol {

}

