//
//  MunAndBabyProductPresenter.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class MunAndBabyProductPresenter {
    //swiftlint:disable all
    weak var output: MunAndBabyProductPresenterOutputProtocol!
    //swiftlint:enable all
}

extension MunAndBabyProductPresenter: MunAndBabyProductInteractorOutputProtocol {
  
}
