//
//  PromotionProductPresenter.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class PromotionProductPresenter {
    //swiftlint:disable all
    weak var output: PromotionProductPresenterOutputProtocol!
    //swiftlint:enable all
}

extension PromotionProductPresenter: PromotionProductInteractorOutputProtocol {
  
}
