//
//  PromotionProductInteractor.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class PromotionProductInteractor/*: PromotionProductViewControllerDataSource */ {
//    //Data passing
//    var dataPassing: AnyObject?
    //swiftlint:disable all
    var output: PromotionProductInteractorOutputProtocol!
    var worker: PromotionProductWorker!
    //swiftlint:enable all
}

extension PromotionProductInteractor: PromotionProductViewControllerOutputProtocol {

}

