//
//  HomeAndLifeProductInteractor.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class HomeAndLifeProductInteractor/*: HomeAndLifeProductViewControllerDataSource */ {
//    //Data passing
//    var dataPassing: AnyObject?
    //swiftlint:disable all
    var output: HomeAndLifeProductInteractorOutputProtocol!
    var worker: HomeAndLifeProductWorker!
    //swiftlint:enable all
}

extension HomeAndLifeProductInteractor: HomeAndLifeProductViewControllerOutputProtocol {

}

