//
//  HomeAndLifeProductPresenter.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

class HomeAndLifeProductPresenter {
    //swiftlint:disable all
    weak var output: HomeAndLifeProductPresenterOutputProtocol!
    //swiftlint:enable all
}

extension HomeAndLifeProductPresenter: HomeAndLifeProductInteractorOutputProtocol {
  
}
