//
//  HomeAndLifeProductConfigurator.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

import UIKit

class HomeAndLifeProductConfigurator {
    
    // MARK: Configuration
    class func viewcontroller() -> HomeAndLifeProductViewController {
//        let viewController = HomeAndLifeProductViewController(nibName: "HomeAndLifeProductViewController", bundle: nil)
        let viewController = HomeAndLifeProductViewController(itemInfo: "FOLLOWING")

        
        let presenter = HomeAndLifeProductPresenter()
        presenter.output = viewController
        
        let interactor = HomeAndLifeProductInteractor()
        interactor.output = presenter
        
        let router = HomeAndLifeProductRouter()
        router.viewController = viewController

//        //Data passing
//        router.dataSource = interactor
        
        viewController.output = interactor
        viewController.router = router
        
        return viewController
    }
}

//// MARK: Data passing
//protocol HomeAndLifeProductViewControllerDataSource: class {
//    //Must be a struct model
//    var dataPassing: AnyObject? {
//        get set
//    }
//}

// MARK: View Interface
protocol HomeAndLifeProductViewControllerOutputProtocol {

}

// MARK: Interactor Interface
protocol HomeAndLifeProductInteractorOutputProtocol {

}

// MARK: Presenter Interface
protocol HomeAndLifeProductPresenterOutputProtocol: class {
    
}

// MARK: Router
protocol HomeAndLifeProductRouterProtocol {

}
