//
//  HomeAndLifeProductViewModel.swift
//  BunnerShopping
//
//  Created Tuan Anh on 2/8/19.
//  Copyright © 2019 Savvycom. All rights reserved.
//
//  Template generated by Savvycom
//

struct HomeAndLifeProductModel {
    struct Request {
        
    }
    
    struct Response {
        
    }
    
    struct ViewModel {
        
    }
}
